# Generated by Django 6.0 on 2026-03-28 20:21

from django.db import migrations, models




class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bd_models', '0014_alter_ball_options_alter_ballinstance_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lootbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, help_text='The name of the lootbox')),
                ('price_multiplier', models.IntegerField(default=1, help_text='The price multiplier for this lootbox; eg. tiers.')),
                ('emoji', models.CharField(default='🎁', help_text='The emoji for the lootbox. Can be an emoji id', max_length=50)),
                ("special_chance", models.IntegerField(help_text="Chance in percentage to get a special", default=2))
            ],
        ),
        migrations.CreateModel(
            name='LootSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('economy', models.BooleanField(help_text='Enables economy settings')),
                ('ball_instance_price', models.IntegerField(default=1, help_text='How many balls get sacrificed for a lootbox')),
                ('economy_price', models.IntegerField(default=100, help_text='How much money gets used to obtain a lootbox')),
                ('rig_multiplier', models.IntegerField(default=100, help_text='The bias towards common balls')),
            ],
        ),

    ]
