# Generated by Django 6.0 on 2026-03-28 20:21

from django.db import migrations, models


def default_box(apps, schema_editor):
    Lootbox = apps.get_model('lootboxes', 'Lootbox')

    Lootbox.objects.get_or_create(name="lite", price_multiplier=1, emoji="🎁", special_chance=1)
    Lootbox.objects.get_or_create(name="pro", price_multiplier=2, emoji="🎁💎", special_chance=2)
    Lootbox.objects.get_or_create(name="pro max", price_multiplier=3, emoji="🎁💎💎", special_chance=3)
    Lootbox.objects.get_or_create(name="pro max ultimate", price_multiplier=10, emoji="🎁💎💎💎", special_chance=10)


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ('lootboxes', '0001_initial'),
    ]

    operations = [
        
        migrations.RunPython(default_box),

    ]
