# Generated by Django 6.0 on 2026-03-28 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lootboxes', '0002_funkyshit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lootbox',
            options={'verbose_name': 'Lootbox', 'verbose_name_plural': 'Lootboxes'},
        ),
        migrations.AlterModelOptions(
            name='lootsettings',
            options={'verbose_name': 'Lootbox Setting', 'verbose_name_plural': 'Lootbox Settings'},
        ),
    ]
