# Generated by Django 6.0 on 2026-03-28 20:21

from django.db import migrations, models


def default_settings(apps, schema_editor):
    LootSettings = apps.get_model('lootboxes', 'LootSettings')

    LootSettings.objects.get_or_create(economy=False, ball_instance_price=2, economy_price=100, rig_multiplier=2)


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ('lootboxes', '0003_alter_lootbox_options_alter_lootsettings_options'),
    ]

    operations = [
        
        migrations.RunPython(default_settings),

    ]
