# Generated by Django 6.0 on 2026-03-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lootboxes', '0004_funkysettingshit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lootsettings',
            name='rig_multiplier',
            field=models.IntegerField(default=1, help_text='The bias towards common balls'),
        ),
    ]
