# Generated by Django 6.0 on 2026-03-29 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_models', '0014_alter_ball_options_alter_ballinstance_options_and_more'),
        ('lootboxes', '0005_alter_lootsettings_rig_multiplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerLootbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lootbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_lootbox', to='lootboxes.lootbox')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_lootbox', to='bd_models.player')),
            ],
            options={
                'verbose_name': 'Player Lootbox',
                'verbose_name_plural': 'Player Lootboxes',
            },
        ),
    ]
