# Generated by Django 6.0 on 2026-03-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lootboxes', '0006_lootbox_special_chance_playerlootbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lootbox',
            name='emoji',
            field=models.CharField(default='🎁', help_text='The emoji for the lootbox.', max_length=50),
        ),
    ]
